<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <!-- Cho phép chạy test song song theo class, tuần tự trong mỗi class -->
    <Parallelism>1</Parallelism>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright.NUnit" Version="1.49.0" />
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.env" CopyToOutputDirectory="PreserveNewest" />
    <None Update=".runsettings" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
